version: "3.9"

services:
  app:
    build: ./app
    container_name: app-service
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: postgres:latest
    container_name: postgres-service
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRESS_DB}
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - appnet

networks:
  appnet:

volumes:
  pgdata:
